### PR TITLE
isScriptHashInput logic fix

### LINKED ISSUE #344: RangeError: Trying to access beyond buffer length
I am having an issue where we get a stack trace thrown when we load up multi-sig transactions from a large amount of inputs. I altered the "works for the P2SH multisig case" test case to demonstrate. 

Stack trace:
```
RangeError: Trying to access beyond buffer length
      at checkOffset (buffer.js:582:11)
      at Buffer.readUInt32LE (buffer.js:642:5)
      at Object.readPushDataInt (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/bufferutils.js:42:21)
      at Function.Script.fromBuffer (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/script.js:40:27)
      at isScriptHashInput (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/scripts.js:73:29)
      at classifyInput (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/scripts.js:142:14)
      at isScriptHashInput (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/scripts.js:75:10)
      at Object.classifyInput (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/scripts.js:142:14)
      at /Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/transaction_builder.js:47:30
      at Array.forEach (native)
      at Function.TransactionBuilder.fromTransaction (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/src/transaction_builder.js:37:19)
      at Context.<anonymous> (/Users/yodasan/bitcoin-dev/bitcoinjs-lib/test/transaction_builder.js:325:39)
      at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:374:10)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:299:14)
      at /usr/local/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:248:23)
      at Object._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:330:15)
```

```javascript
it('reading large multi-sig transaction from hex', function() {
        var privKeys = [
            "91avARGdfge8E4tZfYLoxeJ5sGBdNJQH4kvjJoQFacbgwmaKkrx",
            "91avARGdfge8E4tZfYLoxeJ5sGBdNJQH4kvjJoQFacbgww7vXtT"
        ].map(ECKey.fromWIF)
        var redeemScript = Script.fromASM("OP_2 0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8 04c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee51ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a OP_2 OP_CHECKMULTISIG")

        var numberOfInputs = 300;

        for(var i=0; i < numberOfInputs; i++) {
            txb.addInput("4971f016798a167331bcbc67248313fbc444c6e92e4416efd06964425588f5cf", i);
        }

        txb.addOutput("1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH", 10000)

        for(i=0; i < numberOfInputs; i++) {
            txb.sign(i, privKeys[0], redeemScript)
        }


        var tx = txb.buildIncomplete()
        var hexOutputOne = tx.toHex();

        var txb2 = TransactionBuilder.fromTransaction(tx)
    })
```

### PR DESCRIPTION
**Pull request by dcousens**
This PR fixes a small mistake in `isScriptHashInput` which meant a script would throw during classification of a `Script` rather than return false.

It fixes #344 properly, despite the original test case being fixed by #354.

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -70,7 +70,13 @@ function isScriptHashInput(script, allowIncomplete) {
   if (!Buffer.isBuffer(lastChunk)) return false
 
   var scriptSig = Script.fromChunks(script.chunks.slice(0, -1))
-  var scriptPubKey = Script.fromBuffer(lastChunk)
+  var scriptPubKey
+
+  try {
+    scriptPubKey = Script.fromBuffer(lastChunk)
+  } catch (e) {
```
Comment (dcousens) [inline src/scripts.js]: I wonder if we should be checking specifically for a `RangeError` vs this catch all...

**Comment by dcousens** [comment]
Will release `1.4.4` after this is merged.

File: src/scripts.js (hunk 1 above)
Comment (weilu) [inline src/scripts.js]: I was wondering the same. How about catching all for now and `console.debug` the exception just in case someone may wonder at which stage the classification returned. Hopefully they report back if it's an unexpected case.

**Comment by dcousens** [comment]
Going to merge, @weilu if you could still review post-hoc that'd be awesome. :)

**Comment by weilu** [comment]
I did review and suggested that we `console.debug` the exception caught. The rest looks good

File: src/scripts.js (hunk 1 above)
Comment (dcousens) [inline src/scripts.js]: This is an interesting concept, how would this be any different than returning a `console.debug` for every other instance where it returned false?
