### PR TITLE
Fix taproot sig validation again.

### LINKED ISSUE #1934: PSBT Taproot Input Validation Issue
Hello again,

I have updated to 6.1.2 and am now seeing some new input validation errors on known valid inputs.  I have included an example which was signed in bitcoin-cli

```
bitcoin-cli walletprocesspsbt "{unsigned}" true "SINGLE|ANYONECANPAY" false false
```
which results in the following signed psbt:

```
{
  "tx": {
    "txid": "4810ff15141bd2d7fca4dc4e8fc2f361c716d721f2e221889a2639459d180fc4",
    "hash": "4810ff15141bd2d7fca4dc4e8fc2f361c716d721f2e221889a2639459d180fc4",
    "version": 2,
    "size": 94,
    "vsize": 94,
    "weight": 376,
    "locktime": 0,
    "vin": [
      {
        "txid": "59edb28a4c0c6a9fb319ae6f4e8d5f979b44e786fa127ad012d1eeda83cd944e",
        "vout": 0,
        "scriptSig": {
          "asm": "",
          "hex": ""
        },
        "sequence": 4294967295
      }
    ],
    "vout": [
      {
        "value": 9.90000000,
        "n": 0,
        "scriptPubKey": {
          "asm": "1 2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
          "desc": "rawtr(2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6)#tfj37s9y",
          "hex": "51202252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
          "address": "bc1pyffrxlgln72gtxz0y7cqlkl76n0nsghxm8lm4g82s8jkp0806knqclmd55",
          "type": "witness_v1_taproot"
        }
      }
    ]
  },
  "global_xpubs": [
  ],
  "psbt_version": 0,
  "proprietary": [
  ],
  "unknown": {
  },
  "inputs": [
    {
      "witness_utxo": {
        "amount": 0.00010000,
        "scriptPubKey": {
          "asm": "1 2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
          "desc": "rawtr(2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6)#tfj37s9y",
          "hex": "51202252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
          "address": "bc1pyffrxlgln72gtxz0y7cqlkl76n0nsghxm8lm4g82s8jkp0806knqclmd55",
          "type": "witness_v1_taproot"
        }
      },
      "non_witness_utxo": {
        "txid": "59edb28a4c0c6a9fb319ae6f4e8d5f979b44e786fa127ad012d1eeda83cd944e",
        "hash": "59edb28a4c0c6a9fb319ae6f4e8d5f979b44e786fa127ad012d1eeda83cd944e",
        "version": 1,
        "size": 94,
        "vsize": 94,
        "weight": 376,
        "locktime": 0,
        "vin": [
          {
            "txid": "5d54d7f8e1c17bcf29e5765ab0f40af873a55313c50245ec7eba41427c9afff1",
            "vout": 0,
            "scriptSig": {
              "asm": "",
              "hex": ""
            },
            "sequence": 4294967293
          }
        ],
        "vout": [
          {
            "value": 0.00010000,
            "n": 0,
            "scriptPubKey": {
              "asm": "1 2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
              "desc": "rawtr(2252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6)#tfj37s9y",
              "hex": "51202252337d1f9f9485984f27b00fdbfed4df3822e6d9ffbaa0ea81e560bcefd5a6",
              "address": "bc1pyffrxlgln72gtxz0y7cqlkl76n0nsghxm8lm4g82s8jkp0806knqclmd55",
              "type": "witness_v1_taproot"
            }
          }
        ]
      },
      "sighash": "SINGLE|ANYONECANPAY",
      "taproot_key_path_sig": "643034e6a8dd130e0563ee010f48a61ed0ce4e3b32fae84c76c9478f4cc4a26643a85f8596b9c1556b74a61e6b9056fe5a2a6bb6a5da961864c946bdd4b4eb0383",
      "taproot_internal_key": "8ee617c48a7238c553604be5df980389d0a6fef508099cae34d64a68fcfd7710"
    }
  ],
  "outputs": [
    {
      "taproot_internal_key": "8ee617c48a7238c553604be5df980389d0a6fef508099cae34d64a68fcfd7710"
    }
  ],
  "fee": -9.89990000
}
```

Sparrow Wallet also confirms this is a valid signature.  However, bitcoinjs-lib appears to fail in the validator.  I have created a test case which demonstrates this.  

https://github.com/timechainz/bitcoinjs-lib-psbt-validation/blob/db3d3bd20f57a89f58f59fa78d641001c6f50fcc/validate-taproot-input.js#LL33C1-L33C1

Any ideas would be appreciated.  Thanks!

### PR DESCRIPTION
**Pull request by junderw**
Fixes #1934 

The last PR made the "should be invalid" sig invalid because I was chopping off the wrong byte of the 65 byte signature.

After fixing it, I noticed we didn't actually fix the previous issue either.

This time we actually fixed the issue.

The problem was the assumption that the transaction is always using the "tweak the internal pubkey with a hash of itself" method.

Removing that assumption should fix the issue.

@motorina0 Please review the source and see my comments below first.

### CODE REVIEW

**Comment by junderw** [comment]
Unit tests are broken...

This code is used in signing too...

File: ts_src/psbt.ts [hunk 1]
```diff
@@ -1743,8 +1754,8 @@ function getTaprootHashesForSig(
 
   const hashes = [];
   if (input.tapInternalKey && !tapLeafHashToSign) {
-    const outputKey = tweakInternalPubKey(inputIndex, input);
-    if (toXOnly(pubkey).equals(outputKey)) {
+    const outputKey = getPrevoutTaprootKey(inputIndex, input, cache);
```
Comment (junderw) [inline ts_src/psbt.ts:1757]: This part is breaking one of the test vectors in the unit test for signing.

The test vector says `Sign PSBT with 3 inputs [P2PKH, P2TR (key-path), P2WPKH]` and at this point.

This is confusing...

```
ECPair keypair (pubkey)   4fef5c5163bea69a93e74a59672bbeb081837077cb94cfa6e481a5cf00d8ab18
tweak(tapInternalKey)     4fef5c5163bea69a93e74a59672bbeb081837077cb94cfa6e481a5cf00d8ab18

taproot prevOutput key    9421e734b0f9d2c467ea7dd197c61acb4467cdcbc9f4cb0c571f8b63a5c40cae
input.tapInternalKey      9421e734b0f9d2c467ea7dd197c61acb4467cdcbc9f4cb0c571f8b63a5c40cae
```

The tapInternalKey and the prevout script key are the same, and the WIF for the keypair is the self-tweaked version of tapInternalKey/prevOutputKey.

I think this test vector is incorrect...

Comment (junderw) [reply ts_src/psbt.ts:1757]:
```
> p.data.inputs[1].witnessUtxo
{
  script: <Buffer 51 20 94 21 e7 34 b0 f9 d2 c4 67 ea 7d d1 97 c6 1a cb 44 67 cd cb c9 f4 cb 0c 57 1f 8b 63 a5 c4 0c ae>,
  value: 67000
}
> p.data.inputs[1].tapInternalKey
<Buffer 94 21 e7 34 b0 f9 d2 c4 67 ea 7d d1 97 c6 1a cb 44 67 cd cb c9 f4 cb 0c 57 1f 8b 63 a5 c4 0c ae>
```

**Comment by junderw** [comment]
In the end, a taproot signature is a signature with the key in the previous output, so when we call validateSignatures with a pubkey it should be only the prevout script pubkey we care about.

Perhaps we should make another method to verify if a given pubkey will match the prevout script if it is tweaked...?

Anywho... this is a big change so I've decided not to rush the publish.

**Comment by junderw** [comment]
Re: test vector... how were these generated? btw

**Comment by junderw** [comment]
@motorina0 Please post-publish review if possible. 6.1.2 is broken, so I will release this ASAP.
