### PR TITLE
Re #833: fix bug when dealing with incomplete P2SH/P2WSH inputs.

### LINKED ISSUE #833: buildIncomplete fails for unsigned P2SH inputs
I am trying to write test cases for sending an unsigned transaction P2SH transaction to my service, but I'm unable to get the hex because the `buildIncomplete` function fails with a strange error. See below for bug repro:

```
var b = require('bitcoinjs-lib');
var inp = Buffer.from('010000000173120703f67318aef51f7251272a6816d3f7523bb25e34b136d80be959391c100000000000ffffffff0100c817a80400000017a91471a8ec07ff69c6c4fee489184c462a9b1b9237488700000000', 'hex') // arbitrary P2SH input
var inpTx = b.Transaction.fromBuffer(inp)

var txb = new b.TransactionBuilder(b.networks.testnet)
txb.addInput(inpTx, 0)
txb.addOutput(b.address.toOutputScript('2NAkqp5xffoomp5RLBcakuGpZ12GU4twdz4', b.networks.testnet), 1e8) // arbitrary output

txb.buildIncomplete()
```

produces the error

```
Error: Impossible to sign this type
    at buildInput (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:408:13)
    at /Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:614:18
    at Array.forEach (native)
    at TransactionBuilder.__build (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:611:15)
    at TransactionBuilder.buildIncomplete (/Users/alex/dev/bitcoinjs-lib/src/transaction_builder.js:600:15)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)

```

Based on reading transaction_builder.js it looks like the `buildInput` function assumes the input's `redeemScriptType` would have been set. I would write up a PR but don't know enough about bitcoinjs-lib to know if this is a simple fix or requires a deeper reworking of the txn build/sign flow. Suggestions appreciated!

### PR DESCRIPTION
**Pull request by afk11**
Should be able to deal with incomplete P2SH/P2WSH inputs when allowIncomplete is set. Incorporates suggestion from @Melvillian and does similar for P2WSH, adding test cases for p2sh/p2wsh/p2wpkh.

Fixes #833

### CODE REVIEW

File: test/transaction_builder.js [hunk 1]
```diff
@@ -366,6 +366,38 @@ describe('TransactionBuilder', function () {
...
       assert(tx)
     })
+
+    it('for incomplete P2SH with 0 signatures', function () {
+      var inp = Buffer.from('010000000173120703f67318aef51f7251272a6816d3f7523bb25e34b136d80be959391c100000000000ffffffff0100c817a80400000017a91471a8ec07ff69c6c4fee489184c462a9b1b9237488700000000', 'hex') // arbitrary P2SH input
+      var inpTx = Transaction.fromBuffer(inp)
+
+      var txb = new TransactionBuilder(NETWORKS.testnet)
+      txb.addInput(inpTx, 0)
+      txb.addOutput(baddress.toOutputScript('2NAkqp5xffoomp5RLBcakuGpZ12GU4twdz4', NETWORKS.testnet), 1e8) // arbitrary output
```
Comment (dcousens) [inline test/transaction_builder.js]: Can you remove the redundant `toOutputScript`? 
This is done by `addOutput` anyway

File: src/transaction_builder.js [hunk 2]
```diff
@@ -406,7 +406,7 @@ function buildInput (input, allowIncomplete) {
   if (scriptType === bscript.types.P2SH) {
     // We can remove this error later when we have a guarantee prepareInput
     // rejects unsignable scripts - it MUST be signable at this point.
-    if (P2SH.indexOf(input.redeemScriptType) === -1) {
+    if (P2SH.indexOf(input.redeemScriptType) === -1 && !allowIncomplete) {
```
Comment (Melvillian) [inline src/transaction_builder.js]: down in line 417, I think it should be

```
if (input.redeemScriptType) {
  scriptType = input.redeemScriptType
}
```
because otherwise `scriptType` will end up getting set to undefined in the case where there is no `input.redeemScriptType`.

File: src/transaction_builder.js [hunk 3]
```diff
@@ -422,16 +422,13 @@ function buildInput (input, allowIncomplete) {
...
+    if (SIGNABLE.indexOf(input.witnessScriptType) === -1 && !allowIncomplete) {
+      throw new Error('Impossible to sign this type')
+    } else if (SIGNABLE.indexOf(input.witnessScriptType) !== -1) {
       witness = buildStack(input.witnessScriptType, input.signatures, input.pubKeys, allowIncomplete)
       witness.push(input.witnessScript)
-    } else {
-      // We can remove this error later when we have a guarantee prepareInput
-      // rejects unsignble scripts - it MUST be signable at this point.
-      throw new Error()
+      scriptType = input.witnessScriptType
```
Comment (Melvillian) [inline src/transaction_builder.js]:
```
if (input.witnessScriptType) {
  scriptType = input.witnessScriptType
}
```

**Comment by afk11** [comment]
Hi, you are right, I saw these quite late last night. I'll get a chance to revisit it later.. That whole function is a messy, there's ways to combine it all together if we had the scriptPubKey.. Other comments on this were posted on #835.

File: src/transaction_builder.js (hunk 3 above)
Comment (Melvillian) [inline src/transaction_builder.js]: ignore this comment, the `else if` check above assures `input.witnessScriptType` will be defined

**Comment by afk11** [comment]
> it will end up setting script to an array with the 0 byte ([0]).

ok - moving p2sh=true somewhere better makes this go away.
